import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", ...defaultTheme.fontFamily.sans],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) * 0.8)",
        sm: "calc(var(--radius) * 0.6)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    // Status colors - light mode
    "bg-emerald-50",
    "text-emerald-700",
    "border-emerald-200",
    "border-emerald-300",
    "bg-amber-50",
    "text-amber-700",
    "border-amber-300",
    "bg-red-50",
    "text-red-700",
    "border-red-300",
    "bg-blue-50",
    "text-blue-700",
    "border-blue-300",
    "bg-zinc-50",
    "text-zinc-500",
    "border-zinc-200",
    "bg-slate-50",
    "text-slate-700",
    "border-slate-300",
    // Status colors - dark mode
    "dark:bg-emerald-950",
    "dark:bg-emerald-950/50",
    "dark:text-emerald-300",
    "dark:border-emerald-800",
    "dark:bg-amber-950",
    "dark:text-amber-300",
    "dark:border-amber-800",
    "dark:bg-red-950",
    "dark:text-red-300",
    "dark:border-red-800",
    "dark:bg-blue-950",
    "dark:text-blue-300",
    "dark:border-blue-800",
    "dark:bg-zinc-900/50",
    "dark:text-zinc-400",
    "dark:border-zinc-700",
    "dark:bg-slate-950",
    "dark:text-slate-300",
    "dark:border-slate-800",
    // Type colors
    "text-amber-600",
    "dark:text-amber-400",
    "bg-amber-100",
    "dark:bg-amber-900/30",
    "text-blue-600",
    "dark:text-blue-400",
    "bg-blue-100",
    "dark:bg-blue-900/30",
  ],
};

export default config;
